### ISSUE TITLE
How did you replicate the result of EAEMR?

### ISSUE THREAD

**Issue by zhuang-li** [thunlp/ContinualRE#3]
Hi, I tried to replicate the result of EAEMR. And I went to the original code but I could not replicate the result. It seems you implement it well and show the performance of EAEMR in your paper. So I tried to borrow your code. 

But I found that in your implementation of the EAEMR, the alignment model, the core part of EAEMR, is not used. Is it a bug or something? Can you share your wisdom with me? Thank you!

**Comment by THUCSTHanxu13** [comment]
I directly use the released code of EAEMR for my experiments. In fact,  the released code of EAEMR can achieve better results than the reported ones in the paper of EAEMR. 

To this end, in our paper, the reported results of EAEMR come from their code rather than their paper.
