### ISSUE TITLE
关于关系的表示和相似性度量

### ISSUE THREAD

**Issue by Cyunong** [thunlp/ContinualRE#4]
您好，阅读完您的代码和论文后有些疑问：
1. 论文中说使用训练样本的语义表示和关系的语义表示采用余弦相似度进行度量，但似乎代码中并没用使用网络对关系本身学习语义向量，而是使用了label本身来和样本计算crossEntropy？
2. 代码在计算prototype时用同一个BiLSTM网络提取关系和样本的特征，这样是不是不太合适呢？
3. 代码的实现似乎不需要用到数据集中的negative label？

希望您能解答我的疑惑，这对我帮助很大，谢谢！

**Comment by THUCSTHanxu13** [comment]
1. 如果你仔细看crossEntropy的含义的话，在softmax之前那个线性操作，本质上是算到各个类的分界平面的距离，线性操作的矩阵就是分界平面的法向量，这个就是每个关系的特征。
2. 我们要做的就是约束BiLSTM，你要是采用两个BiLSTM的话就很神奇，本质上我们要做的就是希望新的BiLSTM能继承老BiLSTM

**Comment by THUCSTHanxu13** [comment]
3. Negative Label主要是测试的时候用，NAACL那个baseline需要negative sampling来训练一个类似孪生网络的双塔模型，我的模型不太需要，不过数据里面也放上了
